name: Deploy to Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: .
          target: ${{ vars.SSH_PATH }}

      - name: Stop Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.SSH_PATH }}
            docker compose down

      - name: Start Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ vars.SSH_PATH }}
            docker compose up -d

      - name: Wait for master to be ready
        run: |
          until [ "$(curl -s -o /dev/null -w '%{http_code}' https://smokeping.treudler.net/smokeping/smokeping.cgi)" = "200" ]; do
            sleep 1
          done

      - name: Restart Slave - BartenbachStephanGbR-MyLoc
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SLAVE_SSH_HOST_BARTENBACH }}
          username: ${{ vars.SLAVE_SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/smokeping-slave && docker compose restart

      - name: Restart Slave - Oracle-Frankfurt
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SLAVE_SSH_HOST_ORACLE }}
          username: ${{ vars.SLAVE_SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/smokeping-slave && docker compose restart
